title: GOGO
subtitle: 面朝大海，春暖花开
description: GOGOYAO 的技术学习与记录
author: GOGOYAO
language: zh-CN
timezone: Asia/Shanghai
url: https://gogoyao.github.io
root: /
permalink: :year/:month/:day/:title/
source_dir: content
public_dir: public
theme: ayer
future: false
render_drafts: false
exclude:
  - "interactive/**"
index_generator:
  per_page: 10
  order_by: -date
archive_generator:
  per_page: 20
  yearly: true
  monthly: true
category_generator:
  per_page: 20
tag_generator:
  per_page: 20
highlight:
  enable: true
  line_number: true
updated_option: date
